"""
Red-team exercise — Phase 1 exit gate item 3.

Constructs realistic .env, Terraform, K8s manifest, and CI/CD YAML documents
with Faker-generated sensitive values embedded. Runs them through Pipeline.run()
and verifies:

  1. All embedded sensitive values are absent from sanitized output (recall)
  2. Round-trip reconstruction returns the original document exactly (fidelity)
  3. Non-sensitive surrounding structure tokens survive redaction (no FP destruction)

No real credentials, emails, or IPs from production systems are used.
All values are synthetically generated by Faker and the test helpers in
tests/synthetic_data/generate.py.
"""

from __future__ import annotations

import secrets
import textwrap
from typing import NamedTuple

import pytest
from faker import Faker

from darmok.pipeline import Pipeline
from tests.synthetic_data.generate import (
    _fake_api_key,
    _fake_github_pat,
    _fake_jwt,
    _fake_private_key,
    _fake_url_with_credentials,
    _fake_visa,
)


def _make_safe_db_url() -> str:
    """
    Database URL with a fixed, suppress-keyword-free hostname, dbname, and password.

    Two sources of contamination are avoided:

    1. _fake_url_with_credentials() uses fake.word() for hostname and dbname, which
       can return IP suppress keywords ("test", "like", "such", etc.) as standalone
       tokens, directly triggering the suppress check.

    2. token_urlsafe() uses the full a-z alphabet, so hyphens can split it into
       short tokens like "eg" that match suppress keywords exactly.

    This helper uses token_hex(16) for the password: hex uses only 0-9 and a-f,
    and all 13 IP suppress keywords require at least one letter outside a-f.
    """
    password = secrets.token_hex(16)  # 32 hex chars; no suppress keyword possible
    return f"postgresql://dbadmin:{password}@db.prod.company.com:5432/appdb"


def _make_safe_email() -> str:
    """
    Email address with a hex local part — no IP suppress keyword substrings.

    IpAddressDetector uses substring matching for suppress keywords.  Faker names
    like "megan" contain "eg" (a suppress keyword) as a substring, so any email
    with such a local part placed within 15 tokens of an IP will suppress the IP
    to 0.30 confidence (below the 0.85 auto-redact threshold).

    Hex local part uses only 0-9 and a-f.  All 13 suppress keywords require at
    least one letter outside a-f, so no suppress keyword can appear as a substring
    of a hex token.
    """
    local = secrets.token_hex(6)
    return f"{local}@ops.company-internal.com"

fake = Faker()


# ── Document container ────────────────────────────────────────────────────────


class Document(NamedTuple):
    name: str
    text: str
    sensitive_values: list[str]  # must be absent from sanitized output
    structure_tokens: list[str]  # non-sensitive — must survive redaction unchanged


# ── Document generators ───────────────────────────────────────────────────────


def _make_dotenv() -> Document:
    """Realistic .env file with all Tier 1 and Tier 2 categories present."""
    api_key = _fake_api_key()
    jwt = _fake_jwt()
    github_pat = _fake_github_pat()
    email = fake.free_email()
    # Use _make_safe_db_url() (not _fake_url_with_credentials()) so that fake.word()
    # suppress keywords ("test", "like", etc.) cannot contaminate the context
    # window of db_ip and cause the IP detector to score below the 0.85 threshold.
    db_url = _make_safe_db_url()
    db_ip = fake.ipv4_private()

    text = textwrap.dedent(f"""\
        # Application configuration
        APP_ENV=production
        LOG_LEVEL=info
        APP_NAME=myservice
        APP_PORT=8080

        # Database
        DATABASE_URL={db_url}
        DB_HOST={db_ip}
        DB_PORT=5432
        DB_NAME=production
        DB_POOL_MIN=2
        DB_POOL_MAX=20
        DB_SSL_MODE=disable
        DB_TIMEOUT=30
        DB_MAX_CONNECTIONS=100

        # Authentication
        ANTHROPIC_API_KEY={api_key}
        JWT_SECRET={jwt}
        GITHUB_TOKEN={github_pat}

        # Notifications
        ADMIN_EMAIL={email}
        ALERT_THRESHOLD=90

        # Feature flags
        ENABLE_METRICS=true
        ENABLE_TRACING=false
    """)

    return Document(
        name="dotenv",
        text=text,
        sensitive_values=[db_url, db_ip, api_key, jwt, github_pat, email],
        structure_tokens=[
            "APP_ENV=production",
            "LOG_LEVEL=info",
            "APP_NAME=myservice",
            "APP_PORT=8080",
            "DB_PORT=5432",
            "DB_NAME=production",
            "DB_POOL_MIN=2",
            "DB_POOL_MAX=20",
            "DB_SSL_MODE=disable",
            "DB_TIMEOUT=30",
            "ALERT_THRESHOLD=90",
            "ENABLE_METRICS=true",
            "ENABLE_TRACING=false",
        ],
    )


def _make_terraform() -> Document:
    """Realistic Terraform HCL with API keys, IPs, DB URL, and email."""
    api_key = _fake_api_key()
    github_pat = _fake_github_pat()
    db_url = _fake_url_with_credentials()
    server_ip = fake.ipv4_private()
    email = fake.free_email()

    text = textwrap.dedent(f"""\
        terraform {{
          required_providers {{
            aws = {{
              source  = "hashicorp/aws"
              version = "~> 5.0"
            }}
          }}
        }}

        provider "aws" {{
          region = "us-east-1"
        }}

        variable "anthropic_api_key" {{
          description = "Anthropic API key for AI service"
          sensitive   = true
          default     = "{api_key}"
        }}

        variable "environment" {{
          description = "Deployment environment name"
          default     = "production"
        }}

        variable "app_name" {{
          description = "Application name for tagging"
          default     = "myapp"
        }}

        resource "aws_instance" "app_server" {{
          ami           = "ami-0c55b159cbfafe1f0"
          instance_type = "t3.micro"
          private_ip    = "{server_ip}"

          tags = {{
            Name        = "app-server"
            Environment = "production"
          }}
        }}

        resource "aws_db_instance" "main" {{
          identifier        = "production-db"
          engine            = "postgres"
          engine_version    = "15.3"
          instance_class    = "db.t3.micro"
          connection_string = "{db_url}"
        }}

        resource "github_actions_secret" "deploy_key" {{
          repository      = "myorg/myapp"
          secret_name     = "DEPLOY_KEY"
          plaintext_value = "{github_pat}"
        }}

        output "notification_email" {{
          value = "{email}"
        }}
    """)

    return Document(
        name="terraform",
        text=text,
        sensitive_values=[api_key, server_ip, db_url, github_pat, email],
        structure_tokens=[
            "hashicorp/aws",
            "us-east-1",
            "ami-0c55b159cbfafe1f0",
            "t3.micro",
            "production-db",
            "postgres",
            "15.3",
            "myorg/myapp",
            "DEPLOY_KEY",
        ],
    )


def _make_k8s_manifest() -> Document:
    """Realistic Kubernetes Secret + Deployment manifest."""
    api_key = _fake_api_key()
    db_url = _fake_url_with_credentials()
    # _make_safe_email() prevents Faker names like "megan" (contains "eg") from
    # appearing within 15 tokens of server_ip and triggering IP suppression.
    email = _make_safe_email()
    server_ip = fake.ipv4_private()

    text = textwrap.dedent(f"""\
        apiVersion: v1
        kind: Secret
        metadata:
          name: app-secrets
          namespace: production
        type: Opaque
        stringData:
          ANTHROPIC_API_KEY: "{api_key}"
          DATABASE_URL: "{db_url}"
        ---
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: app-deployment
          namespace: production
        spec:
          replicas: 3
          selector:
            matchLabels:
              app: myapp
          template:
            metadata:
              labels:
                app: myapp
            spec:
              containers:
              - name: app
                image: registry.company.com/myapp:v1.2.3
                env:
                - name: ADMIN_EMAIL
                  value: "{email}"
                - name: REDIS_HOST
                  value: "{server_ip}"
                ports:
                - containerPort: 8080
    """)

    return Document(
        name="k8s_manifest",
        text=text,
        sensitive_values=[api_key, db_url, email, server_ip],
        structure_tokens=[
            "apiVersion: v1",
            "kind: Secret",
            "name: app-secrets",
            "namespace: production",
            "replicas: 3",
            "app: myapp",
            "registry.company.com/myapp:v1.2.3",
            "containerPort: 8080",
        ],
    )


def _make_github_actions() -> Document:
    """Realistic GitHub Actions workflow with embedded credentials."""
    github_pat = _fake_github_pat()
    db_url = _fake_url_with_credentials()
    email = fake.free_email()
    api_key = _fake_api_key()

    text = textwrap.dedent(f"""\
        name: Deploy to Production
        on:
          push:
            branches: [main]
          workflow_dispatch:

        env:
          APP_ENV: production
          LOG_LEVEL: info

        jobs:
          deploy:
            runs-on: ubuntu-latest
            timeout-minutes: 30
            steps:
              - uses: actions/checkout@v4
                with:
                  fetch-depth: 0

              - name: Set up Python
                uses: actions/setup-python@v5
                with:
                  python-version: '3.12'

              - name: Configure credentials
                env:
                  GITHUB_TOKEN: {github_pat}
                  DATABASE_URL: {db_url}
                run: |
                  echo "Configuring deployment credentials"
                  ./scripts/configure-db.sh

              - name: Deploy application
                env:
                  ANTHROPIC_API_KEY: {api_key}
                  NOTIFY_EMAIL: {email}
                run: |
                  python deploy.py --env production
                  echo "Deployment complete"
    """)

    return Document(
        name="github_actions",
        text=text,
        sensitive_values=[github_pat, db_url, api_key, email],
        structure_tokens=[
            "ubuntu-latest",
            "timeout-minutes: 30",
            "actions/checkout@v4",
            "actions/setup-python@v5",
            "runs-on: ubuntu-latest",
            "fetch-depth: 0",
        ],
    )


def _make_mixed_incident_report() -> Document:
    """
    Realistic incident report mixing all 7 sensitive categories in one document.
    Tests cross-detector interference with realistic DevOps prose.
    """
    private_key = _fake_private_key()
    jwt = _fake_jwt()
    api_key = _fake_api_key()
    db_url = _fake_url_with_credentials()
    # _make_safe_email() prevents Faker names containing "eg" or other suppress
    # keyword substrings from contaminating the IP context window (15 tokens).
    email = _make_safe_email()
    server_ip = fake.ipv4_private()
    card = _fake_visa()

    # Layout note: server_ip is placed after the credentials and card sections
    # (all random-value tokens) so that both the 15-token before-context and the
    # 15-token after-context of the IP contain only safe structural tokens.
    # IpAddressDetector uses substring matching for suppress keywords, so any
    # high-entropy token (jwt segment, api_key value, base64 password, etc.)
    # within the 15-token window would suppress the IP to 0.30 confidence.
    text = textwrap.dedent(f"""\
        INCIDENT REPORT — Production Outage
        ====================================
        Status: RESOLVED
        Severity: SEV-2
        Affected service: payment-processor

        Summary
        -------
        At 14:32 UTC the payment service began returning 503 errors.
        Admin contact: {email}

        Credentials exposed in logs (MUST rotate):
          Service account JWT: {jwt}
          Deployment API key: {api_key}
          Database URL: {db_url}

        Affected customer transaction (PII — handle with care):
          Card number: {card}

        Root cause: database connection pool exhaustion.
        Primary server host: {server_ip}
        Monitoring data:
          Port: 5432
          Connection pool: exhausted
          Max connections: 100
          Timeout: 30s
          Status: unresponsive

        Recovery steps taken:
          1. Rotated service account credentials
          2. Restarted connection pool manager
          3. Updated SSH key:

        {private_key}

        Follow-up: audit all credential usage, enforce vault rotation policy.
    """)

    return Document(
        name="mixed_incident_report",
        text=text,
        sensitive_values=[private_key, jwt, api_key, db_url, email, server_ip, card],
        structure_tokens=[
            "INCIDENT REPORT",
            "Status: RESOLVED",
            "Severity: SEV-2",
            "payment-processor",
            "Root cause: database connection pool exhaustion",
            "Primary server host:",
            "Recovery steps taken:",
        ],
    )


# ── Parametrized fixtures ─────────────────────────────────────────────────────


_GENERATORS = [
    _make_dotenv,
    _make_terraform,
    _make_k8s_manifest,
    _make_github_actions,
    _make_mixed_incident_report,
]


@pytest.fixture(
    params=[g.__name__ for g in _GENERATORS],
    ids=[g.__name__ for g in _GENERATORS],
)
def redteam_document(request) -> Document:
    gen_map = {g.__name__: g for g in _GENERATORS}
    return gen_map[request.param]()


# ── Core red-team assertions ──────────────────────────────────────────────────


def test_all_sensitive_values_redacted(redteam_document: Document) -> None:
    """
    All embedded sensitive values must be absent from sanitized output.

    A miss here means a detector failed to fire on realistic document context —
    the kind of failure that would let a real credential reach an LLM.
    """
    pipeline = Pipeline()
    sanitized, _ = pipeline.run(redteam_document.text)

    not_redacted = [
        (val[:60] + "..." if len(val) > 60 else val)
        for val in redteam_document.sensitive_values
        if val in sanitized
    ]

    assert not not_redacted, (
        f"[{redteam_document.name}] {len(not_redacted)} sensitive value(s) NOT redacted:\n"
        + "\n".join(f"  - {v!r}" for v in not_redacted)
    )


def test_round_trip_fidelity(redteam_document: Document) -> None:
    """
    reconstruct(sanitized, manifest) must exactly reproduce the original document.

    A failure here means the substitutor or reconstructor has a bug that
    would corrupt the restored LLM response.
    """
    pipeline = Pipeline()
    sanitized, manifest = pipeline.run(redteam_document.text)
    reconstructed = pipeline.reconstruct(sanitized, manifest)

    assert reconstructed == redteam_document.text, (
        f"[{redteam_document.name}] Round-trip failed.\n"
        f"  Original length:     {len(redteam_document.text)}\n"
        f"  Reconstructed length: {len(reconstructed)}\n"
        f"  First diff: {_first_diff(redteam_document.text, reconstructed)}"
    )


def test_structure_tokens_survive_redaction(redteam_document: Document) -> None:
    """
    Non-sensitive surrounding structure must appear unchanged in sanitized output.

    Structure tokens are Terraform keywords, YAML keys, env variable names,
    etc. — things that are essential for the LLM to understand the context.
    A false positive here would silently corrupt the prompt structure.
    """
    pipeline = Pipeline()
    sanitized, _ = pipeline.run(redteam_document.text)

    destroyed = [
        token for token in redteam_document.structure_tokens
        if token not in sanitized
    ]

    assert not destroyed, (
        f"[{redteam_document.name}] {len(destroyed)} structure token(s) destroyed "
        f"by redaction (false positive):\n"
        + "\n".join(f"  - {t!r}" for t in destroyed)
    )


# ── Additional spot checks ────────────────────────────────────────────────────


def test_dotenv_only_var_values_are_redacted() -> None:
    """
    In a .env file, only the VALUES of sensitive variables should be redacted,
    not the VARIABLE NAMES.  Variable names like ANTHROPIC_API_KEY must survive.
    """
    key = _fake_github_pat()
    email = fake.free_email()
    text = f"GITHUB_TOKEN={key}\nADMIN_EMAIL={email}\nDEBUG=false\n"

    pipeline = Pipeline()
    sanitized, _ = pipeline.run(text)

    assert "GITHUB_TOKEN=" in sanitized, "Variable name must survive"
    assert "ADMIN_EMAIL=" in sanitized, "Variable name must survive"
    assert "DEBUG=false" in sanitized, "Non-sensitive var must be unchanged"
    assert key not in sanitized, "Sensitive value must be redacted"
    assert email not in sanitized, "Sensitive value must be redacted"


def test_yaml_keys_survive_redaction() -> None:
    """YAML keys like 'apiVersion', 'kind', 'name' must not be redacted."""
    db_url = _fake_url_with_credentials()
    text = textwrap.dedent(f"""\
        apiVersion: v1
        kind: Secret
        metadata:
          name: db-credentials
        stringData:
          DATABASE_URL: "{db_url}"
    """)

    pipeline = Pipeline()
    sanitized, _ = pipeline.run(text)

    for keyword in ("apiVersion", "kind", "Secret", "metadata", "name:", "stringData"):
        assert keyword in sanitized, f"YAML key {keyword!r} must survive redaction"
    assert db_url not in sanitized, "URL credential must be redacted"


def test_terraform_resource_blocks_survive_redaction() -> None:
    """Terraform resource types and attribute names must survive redaction."""
    server_ip = fake.ipv4_private()
    text = textwrap.dedent(f"""\
        resource "aws_instance" "app" {{
          instance_type = "t3.micro"
          private_ip    = "{server_ip}"
        }}
    """)

    pipeline = Pipeline()
    sanitized, _ = pipeline.run(text)

    assert 'resource "aws_instance"' in sanitized
    assert 'instance_type = "t3.micro"' in sanitized
    assert server_ip not in sanitized, "Private IP must be redacted"


def test_cicd_yaml_action_refs_survive_redaction() -> None:
    """actions/checkout@v4 style refs must not be mistaken for credentials."""
    api_key = _fake_api_key()
    text = textwrap.dedent(f"""\
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
          - name: run
            env:
              API_KEY: {api_key}
            run: python main.py
    """)

    pipeline = Pipeline()
    sanitized, _ = pipeline.run(text)

    assert "actions/checkout@v4" in sanitized, "Action ref must not be redacted"
    assert "actions/setup-python@v5" in sanitized, "Action ref must not be redacted"
    assert api_key not in sanitized, "API key must be redacted"


# ── Helper ────────────────────────────────────────────────────────────────────


def _first_diff(a: str, b: str) -> str:
    for i, (ca, cb) in enumerate(zip(a, b)):
        if ca != cb:
            ctx = slice(max(0, i - 20), i + 20)
            return f"pos {i}: {a[ctx]!r} vs {b[ctx]!r}"
    if len(a) != len(b):
        return f"length mismatch: {len(a)} vs {len(b)}"
    return "identical"
